CampusMarket/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversion.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversion/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]
    

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='item_images/category', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    image2 = models.ImageField(upload_to='item_images', blank=True, null=True)
    college = models.CharField(max_length=255)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image','image2','college')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image2': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'college' : forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image','image2','is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image2': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from  . import OnlineSearchAPI
from .forms import NewItemForm, EditItemForm
from .models import Category, Item

def items(request):
    query = request.GET.get('query', '')
    college = request.GET.get('clg', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    data = None
    if college:
        items = items.filter(college__icontains = college)
    if category_id:
        items = items.filter(category_id=category_id)
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
        data = OnlineSearchAPI.get_online_data(query)
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'data' : data,
        'clg' : college,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:4]
    data = OnlineSearchAPI.get_online_data(item.name)
    return render(request, 'item/detail.html', {
        'item': item,
        'data' : data,
        'related_items': related_items
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'detail.css' %}">
<style>
.tagtext::-webkit-scrollbar {
  display: none; 
}
</style>
{% endblock %}
{% block title %}{{ item.name }}{% endblock %}
{% block content %}
<div class="grid grid-cols-1 lg:grid-cols-6  m-4">
    <div class="product lg:col-span-2 bg-bgcolor">
        <div class="allImages">
            <div class="m-3 flex flex-col">
                <div class="flex justify-center">
                    <img class="w-[400px] h-[400px] image" src="{{ item.image.url }}" alt="">
                </div>

                <div class="flex justify-center space-x-3 p-3">
                    <img class="h-14 smimg" id="img1" src="{{ item.image.url }}" alt="">
                    <img class="h-14 smimg" id="img2" src="{{ item.image2.url }}" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="ml-5 mt-10 productInfo lg:col-span-4">
        <h1 class="text-4xl mb-1 font-medium text-center font-serif">{{ item.name }}</h1>
        <hr>
        {% if item.description %}
        <p class="font-medium text-lg text-gray-700">Description:</p>
        <p class=" text-lg font-normal">   {{ item.description }}</p>
        {% endif %}
        <br>
        <p class="font-medium text-lg text-gray-700">Seller: <span class="text-lg font-normal">{{ item.created_by.username }}</span></p>
        <p class="font-medium text-lg text-gray-700">College: <span class="text-lg font-normal">{{ item.college }}</span></p>

        <br>
        <p class="font-medium text-lg text-gray-700">Price: <span class="text-xl font-normal">&#8377; {{ item.price }}</span></p>
        <hr>
        {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <p>This is your item!</p>
            <div class="flex justify-center m-2 mb-10">
                <a href="{% url 'item:edit' item.id %}" class="ml-2 px-6 py-2 rounded-full focus:outline-none bg-green-400 ">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="ml-2 px-6 py-2 rounded-full focus:outline-none bg-orange-500 ">Delete</a>
            </div>
        </div>
        {% else %}
        <div class="flex justify-center m-2 mb-10">
            <a href="{% url 'conversation:new' item.id %}" class="ml-2 px-6 py-2 rounded-full focus:outline-none bg-green-400 ">Contact Seller</a>
        </div>
        {% endif %}
    </div>
</div>
{% if related_items %}
<h2 class="font-extrabold text-xl ml-12 pt-5 text-black mb-4">Related Items</h2>
<div class="grid grid-cols-1 lg:grid-cols-5 gap-4 m-2 bg-fblue p-2 rounded-lg ">
    {% for item in related_items %}
    <a href="{% url 'item:detail' item.id %}" class="flex  lg:flex-col " style="max-width: 150px; ">
        <img src="{{ item.image.url }}" class="w-full hover:scale-105" alt="" style="width: 150px; height: 150px;">
        <div class="flex flex-col  top-1/2 ">
            <h2 class="font-bold tracking-wider text-center">{{ item.name }}</h2>
            <h3 class="font-semibold text-center pb-1">&#8377;{{ item.price }}</h3>
        </div>
    </a>
    {% endfor %}
{% endif %}
</div>
{% if data %}
<h2 class="font-extrabold text-xl ml-12 pt-5 text-black mb-4">Online Results</h2>
<div style="height:600px; overflow: scroll;">
    <div class="grid grid-cols-1 lg:grid-cols-5 gap-4 m-2 bg-fblue p-2 rounded-lg">
        {% for item in data  %}
        <a href="{{ item.url }}" class="flex lg:flex-col" style="max-width: 150px;">
            <img src="{{ item.img }}" class="w-full hover:scale-105" alt="" style="width: 150px; height: 150px;">
            <div class="flex flex-col top-1/2">
                <h2 class="tagtext font-bold tracking-wider text-center" style="max-height:85px; overflow:scroll;">{{ item.title }}</h2>
                <h3 class="font-semibold text-center pb-1">{{ item.price }}</h3>
                <h3 class="font-semibold text-center pb-1">{{ item.provider }}</h3>            
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}
{% block js %}
    {% load static %}
    <script src="{% static 'js/individual.js' %}"></script>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% load static %}
{% block css %} <link rel="stylesheet" href="{% static 'forms.css' %}">{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center p-4 bg-fblue">
    <div class=" w-[80%] lg:w-[45%]">
        <h1 class="mb-6 text-3xl text-center font-semibold">{{ title }}</h1>
     
        <form method="post" action="." enctype="multipart/form-data" class="bg-white shadow-lg rounded-xl px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            <div class="space-y-4">
                {{ form.as_p }}
            </div>
            {% if form.errors or form.non_field_errors %}
            <div class="mt-6 py-4 px-8 text-lg bg-red-100 rounded-xl text-red-700">
                {% for field in form %}
                {{ field.errors }}
                {% endfor %}
                
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button type="submit" class="mt-6 py-4 px-8 text-lg bg-orange-400 hover:bg-orange-500 rounded-xl text-white">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'items.css' %}">
<style>
    .tagtext::-webkit-scrollbar {
      display: none; 
    }
</style>
{% endblock %}
{% block title %}Items{% endblock %}
{% block content %}
<div class="mainbody grid grid-cols-1 lg:grid-cols-6 p-4">
    <div class="filters col-span-1 rounded-md mb-2 bg-fblue lg:mr-2 lg:mb-0 ">
        <div class="pr-4 pl-4 lg:pr-14 lg:pl-10 py-10 lg:py-14 flex flex-col space-y-5 ">
            <div>
                <h1 class="text-2xl lg:text-4xl">Filters</h1>
            </div>
            <form method="get" action="{% url 'item:items' %}">
                <p class="font-semibold">Search by College: </p>
                <input name="clg" value="{{clg}}" type="text" placeholder="Enter college name here" class="py-2">
                <button class="bg-green-300 hover:bg-green-400 rounded-lg mt-2 p-1">Search</button>
            </form>
            <div class="category">
                <h2 class="font-semibold">Category</h2>
                <ul>
                    {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <hr class="my-6">
            <p class="font-semibold">Clear filters</p>
            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-2 px-4 lg:px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>
        </div>
    </div>
    <div class="items bg-fblue rounded-md container p-3 col-span-5">
        <div class="text-center">
            <h1 class="text-3xl lg:text-5xl">Items</h1>
        </div>
        <div class="p-5">
            <h1>{{items|length}} results found</h1>
        </div>
        <div class="grid grid-cols-1 lg:grid-cols-5 gap-4 ">
            {% for item in items %}
            <a href="{% url 'item:detail' item.id %}" class="flex  lg:flex-col mb-5" style="max-width: 200px;">
                <img src="{{item.image.url}}" class="w-full hover:scale-105" alt="" style="width: 200px; height: 200px;">
                <div class="flex flex-col  top-1/2 ">
                    <h2 class="font-bold tracking-wider text-center">{{ item.name }}</h2>
                    <h3 class="font-semibold text-center pb-1">&#8377;{{ item.price }}</h3>
                    <h3 class="italic pl-2 "><span class="font-medium">Seller:</span>{{item.created_by}} | {{item.college}}</h3>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% if data %}
<h2 class="font-extrabold text-xl ml-12 pt-5 text-black mb-4">Online Results</h2>
<div style="height:600px; overflow: scroll;">
    <div class="grid grid-cols-1 lg:grid-cols-5 gap-4 m-2 bg-fblue p-2 rounded-lg">
        {% for item in data  %}
        <a href="{{ item.url }}" class="flex lg:flex-col" style="max-width: 150px;">
            <img src="{{ item.img }}" class="w-full hover:scale-105" alt="" style="width: 150px; height: 150px;">
            <div class="flex flex-col top-1/2">
                <h2 class="tagtext font-bold tracking-wider text-center" style="max-height:85px; overflow:scroll;">{{ item.title }}</h2>
                <h3 class="font-semibold text-center pb-1">{{ item.price }}</h3>
                <h3 class="font-semibold text-center pb-1">{{ item.provider }}</h3>            
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}